[package]
name = "protocol"
version = "0.1.0"
authors = ["Jim Blandy <jimb@red-bean.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.15"
serde = { version = "1.0.89", features = ["derive"] }
